name: Merge

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  test:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3

      - run: go test -timeout 4h ./...

