name: Merge

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3

      - run: |
          if [ "${{github.event_name}}" == "merge_group" ]; then
            go test ./...
          fi

